name: Community submission (JSON)
description: Submit one or more community records (JSON) to be reviewed and approved.
title: "Community submission: "
labels:
  - community
  - submission
body:
  - type: markdown
    attributes:
      value: |
        Submit **one object** or an **array of objects** that matches the community submission [schema](https://github.com/PlaneQuery/OpenAirframes/blob/main/schemas/community_submission.v1.schema.json). Reuse existing tags from the schema when possible.
        
        **Rules (enforced on review/automation):**
        - Each object must include **at least one** of:
          - `registration_number`
          - `transponder_code_hex` (6 uppercase hex chars, e.g., `ABC123`)
          - `openairframes_id`
        - Your contributor name (entered below) will be applied to all objects.
        - `contributor_uuid` is derived from your GitHub account automatically.
        - `creation_timestamp` is created by the system (you may omit it).

        **Optional date scoping:**
        - `start_date` - When the tags become valid (ISO 8601: `YYYY-MM-DD`)
        - `end_date` - When the tags stop being valid (ISO 8601: `YYYY-MM-DD`)

        **Example: single object**
        ```json
        {
            "registration_number": "N12345",
            "tags": {"owner": "John Doe", "photo": "https://example.com/photo.jpg"},
            "start_date": "2025-01-01"
        }
        ```
        **Example: multiple objects (array)**
        ```json
        [
        {
            "registration_number": "N12345",
            "tags": {"internet": "starlink"},
            "start_date": "2025-05-01"
        },
        {
            "registration_number": "N12345",
            "tags": {"owner": "John Doe"},
            "start_date": "2025-01-01",
            "end_date": "2025-07-20"
        },
        {
            "transponder_code_hex": "ABC123",
            "tags": {"internet": "viasat", "owner": "John Doe"}
        }
        ]
        ```

  - type: input
    id: contributor_name
    attributes:
      label: Contributor Name
      description: Your display name for attribution. Leave blank for no attribution. Max 150 characters.
      placeholder: "e.g., JamesBerry.com or leave blank"
    validations:
      required: false

  - type: textarea
    id: submission_json
    attributes:
      label: Submission JSON
      description: |
        Paste JSON directly, OR drag-and-drop a .json file here.
        Must be valid JSON. Do not include contributor_name or contributor_uuid.
      placeholder: |
        Paste JSON here, or drag-and-drop a .json file...
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Notes (optional)
    validations:
      required: false